### ISSUE TITLE
usage

### ISSUE THREAD

**Issue by anotherfinemess84** [CamxxCore/EasyAntiCheat-Emulator#1]
should it be injected or just dropped to game dir.  have you had success on Ragnarok?

**Comment by CamxxCore** [comment]
Replace the EasyAntiCheat_(platform).dll that is inside the game files (typically inside a folder called EasyAntiCheat) with this one. Then replace the launcher with the actual game executable. I have not tested the game you mentioned, unfortunately.

**Comment by anotherfinemess84** [comment]
Thanks however what do you mean replace launcher?

**Comment by anotherfinemess84** [comment]
[https://cdn.discordapp.com/attachments/668839644254961665/798065490739855400/20210111_134649.jpg](url)
